name: 'wait-for-checks'
description: 'Wait for GitHub Status Checks'
author: 'poseidon'
branding:
  icon: check-circle
  color: green
inputs:
  token:
    description: 'GitHub token for reading the status check runs'
    required: true
  interval:
    description: 'Interval or period in seconds to poll GitHub Check Runs'
  timeout:
    description: 'Timeout in seconds to poll GitHub Check Runs'
  delay:
    description: 'Period in seconds to wait before first poll of GitHub Check Runs'
  match_pattern:
    description: 'Regex match GitHub checks that should be watched'
  ignore_pattern:
    description: 'Regex match GitHub checks that should be ignored'
  ignore:
    description: 'GitHub checks that should be ignored (default ignores the current job)'
  success_conclusions:
    description: 'Comma-separated list of conclusion states that should be considered successful'
    default: 'success,skipped'
  timeout_behavior:
    description: 'Behavior when timeout is reached: fail (default), success'
    default: 'fail'
runs:
  using: 'node20'
  main: 'dist/index.js'
